application:
  host: 0.0.0.0
database:
  # New entry!
  require_ssl: true
email_client:
  # Value retrieved from Postmark's API documentation
  base_url: "https://api.postmarkapp.com"
  # Use the single sender email you authorised on Postmark!
  sender_email: "71205902002@stu.ecnu.edu.cn"
